### ISSUE TITLE
PT_BR

### ISSUE THREAD

**Issue by 7sem-nome** [smell-of-curry/pokebedrock-res#23]
`https://github.com/smell-of-curry/pokebedrock-res/blob/5679e2dc508ab47f0da444acab0248af6aedd2e2/texts/language_names.json#L43`

**Comment by 7sem-nome** [comment]
https://github.com/smell-of-curry/pokebedrock-res/blob/5679e2dc508ab47f0da444acab0248af6aedd2e2/texts/language_names.json#L43

**Comment by smell-of-curry** [comment]
?
